apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-xml-stilling
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-xml-stilling
  port: 9020
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 10
    path: /isAlive
  readiness:
    initialDelay: 10
    path: /isAlive
  prometheus:
    enabled: true
    path: /prometheus
  webproxy: true
  vault:
    enabled: true
  ingresses:
    - https://pam-xml-stilling.nais.oera-q.local
  env:
    - name: JDBC_URL
      value: jdbc:postgresql://b27dbvl007.preprod.local/xmlstilling-ws-preprod
    - name: DB_NAME
      value: xmlstilling-ws-preprod
    - name: VAULT_MOUNT_PATH
      value: postgresql/preprod-fss