server:
  port: 9020
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus", "metrics", "info"]
      path-mapping:
        info: "isAlive"
      base-path: "/"
no.nav.security.oidc:
  issuers: loginservice-oidc
  issuer.loginservice-oidc:
    discoveryurl: ${LOGINSERVICE_OIDC_DISCOVERYURI}
    accepted_audience: ${LOGINSERVICE_OIDC_CLIENTID}
    cookie_name: isso-idtoken