server:
  port: 9020
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus", "metrics", "info"]
      path-mapping:
        info: "isAlive"
      base-path: "/"